import { Text } from "@chakra-ui/react";

export const columnsData1 = [
  {
    Header: "#",
    Cell: ({ row }) => <Text>{row.index + 1}</Text>,
  },
  {
    Header: "ID",
    accessor: "_id",
  },
  {
    Header: "Зураг",
    accessor: "pic",
  },
  {
    Header: "Овог",
    accessor: "surname",
  },
  {
    Header: "Нэр",
    accessor: "name",
  },
  {
    Header: "цахим хаяг",
    accessor: "email",
  },
  {
    Header: "ажилтны Id",
    accessor: "empolyee_id",
  },
  {
    Header: "нас",
    accessor: "age",
  },
  {
    Header: "хүйс",
    accessor: "gender",
  },
  {
    Header: "төрсөн өдөр",
    accessor: "date_of_birth",
  },
  {
    Header: "элссэн он",
    accessor: "joining_year",
  },
  {
    Header: "элссэн он",
    accessor: "attdenList",
  },
  {
    Header: "элссэн он",
    accessor: "markList",
  },
  {
    Header: "элссэн он",
    accessor: "pList",
  },
];
export const columnsData2 = [
  {
    id: 1,
    name: "Бат",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaanbaatar",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
  {
    id: 2,
    name: "Бат",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaanbaatar",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
  {
    id: 3,
    name: "eeeeee",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaan",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
    {
      id: 4,
      name: "eeeeee",
      department: "програм хангамж",
      phone: "94741310",
      gender: "Эрэгтэй",
      date: "8/27/2021",
      Address: "Ulaan",
      email: "bat@gmail.com",
      status: "Online",
      degree: "M.Sc., PHD.",
    },
    {
      id: 5,
      name: "eeeeee",
      department: "програм хангамж",
      phone: "94741310",
      gender: "Эрэгтэй",
      date: "8/27/2021",
      Address: "Ulaan",
      email: "bat@gmail.com",
      status: "Online",
      degree: "M.Sc., PHD.",
    },
    {
      id: 6,
      name: "eeeeee",
      department: "програм хангамж",
      phone: "94741310",
      gender: "Эрэгтэй",
      date: "8/27/2021",
      Address: "Ulaan",
      email: "bat@gmail.com",
      status: "Online",
      degree: "M.Sc., PHD.",
    },
    {
      id: 7,
      name: "eeeeee",
      department: "програм хангамж",
      phone: "94741310",
      gender: "Эрэгтэй",
      date: "8/27/2021",
      Address: "Ulaan",
      email: "bat@gmail.com",
      status: "Online",
      degree: "M.Sc., PHD.",
    },
    {
      id: 8,
      name: "eeeeee",
      department: "програм хангамж",
      phone: "94741310",
      gender: "Эрэгтэй",
      date: "8/27/2021",
      Address: "Ulaan",
      email: "bat@gmail.com",
      status: "Online",
      degree: "M.Sc., PHD.",
    },
];
