export const columnsData1 = [
  {
    Header: "ID",
    accessor: "id",
  },
  {
    Header: "Нэр",
    accessor: "name",
  },
  {
    Header: "Хэлтэс",
    accessor: "department",
  },
  {
    Header: "Утас",
    accessor: "phone",
  },
  {
    Header: "Хүйс",
    accessor: "gender",
  },
  {
    Header: "Орсон огноо",
    accessor: "date",
  },
  {
    Header: "Хаяг",
    accessor: "Address",
  },
  {
    Header: "цахим хаяг",
    accessor: "email",
  },
  {
    Header: "Status",
    accessor: "status",
  },
  {
    Header: "Боловсрол",
    accessor: "degree",
  },
];
export const columnsData2 = [
  {
    id: 1,
    name: "Бат",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaanbaatar",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
  {
    id: 2,
    name: "Бат",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaanbaatar",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
  {
    id: 3,
    name: "eeeeee",
    department: "програм хангамж",
    phone: "94741310",
    gender: "Эрэгтэй",
    date: "8/27/2021",
    Address: "Ulaan",
    email: "bat@gmail.com",
    status: "Online",
    degree: "M.Sc., PHD.",
  },
  //   {
  //     id: 4,
  //     name: "eeeeee",
  //     department: "програм хангамж",
  //     phone: "94741310",
  //     gender: "Эрэгтэй",
  //     date: "8/27/2021",
  //     Address: "Ulaan",
  //     email: "bat@gmail.com",
  //     status: "Online",
  //     degree: "M.Sc., PHD.",
  //   },
  //   {
  //     id: 5,
  //     name: "eeeeee",
  //     department: "програм хангамж",
  //     phone: "94741310",
  //     gender: "Эрэгтэй",
  //     date: "8/27/2021",
  //     Address: "Ulaan",
  //     email: "bat@gmail.com",
  //     status: "Online",
  //     degree: "M.Sc., PHD.",
  //   },
  //   {
  //     id: 6,
  //     name: "eeeeee",
  //     department: "програм хангамж",
  //     phone: "94741310",
  //     gender: "Эрэгтэй",
  //     date: "8/27/2021",
  //     Address: "Ulaan",
  //     email: "bat@gmail.com",
  //     status: "Online",
  //     degree: "M.Sc., PHD.",
  //   },
  //   {
  //     id: 7,
  //     name: "eeeeee",
  //     department: "програм хангамж",
  //     phone: "94741310",
  //     gender: "Эрэгтэй",
  //     date: "8/27/2021",
  //     Address: "Ulaan",
  //     email: "bat@gmail.com",
  //     status: "Online",
  //     degree: "M.Sc., PHD.",
  //   },
  //   {
  //     id: 8,
  //     name: "eeeeee",
  //     department: "програм хангамж",
  //     phone: "94741310",
  //     gender: "Эрэгтэй",
  //     date: "8/27/2021",
  //     Address: "Ulaan",
  //     email: "bat@gmail.com",
  //     status: "Online",
  //     degree: "M.Sc., PHD.",
  //   },
];
